#!/usr/bin/env fish

dotnet build && \
cp ./FriendlyPotato/bin/x64/Debug/*.png ~/.xlcore/protonprefix/drive_c/ && \
cp ./FriendlyPotato/bin/x64/Debug/FriendlyPotato.json ~/.xlcore/protonprefix/drive_c/FriendlyPotato.json && \
sed -i 's/"friendly-potato"/"friendly-potato-dev"/g' ~/.xlcore/protonprefix/drive_c/FriendlyPotato.json && \
cp ./FriendlyPotato/bin/x64/Debug/FriendlyPotato.dll ~/.xlcore/protonprefix/drive_c/FriendlyPotato.dll
