# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    tags:
    - '*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore -c Release --output ./output
    - name: Update Repository
      run: |
        #!/bin/bash
        VERSION=${GITHUB_REF#refs/tags/}
        echo $VERSION
#   upload:
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/download-artifact@v4
#       with:
#         name: build-output
#         path: ./output
#     - uses: ryand56/r2-upload-action@latest
#       with:
#         r2-account-id: ${{ secrets.R2_ACCOUNT_ID }}
#         r2-access-key-id: ${{ secrets.R2_ACCESS_KEY_ID }}
#         r2-secret-access-key: ${{ secrets.R2_SECRET_ACCESS_KEY }}
#         r2-bucket: ${{ secrets.R2_BUCKET }}
#         source-dir: ./output
#         destination-dir: ./friendly-potato
